(() => {
  'use strict';
  const C=window.JZE_CONFIG,$=s=>document.querySelector(s);let snapshot={teams:[],proofs:[],sportifs:[],touristes:[]};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('is-visible');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('is-visible'),2400)};
  function base(){const u=String(C.apiUrl||'').trim();if(!/^https:\/\//i.test(u))throw Error('URL Apps Script invalide');return u}
  async function get(params){const q=Object.entries(params).map(([k,v])=>`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join('&');const u=`${base()}${base().includes('?')?'&':'?'}${q}`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
  async function post(params){const b=new URLSearchParams();Object.entries(params).forEach(([k,v])=>b.set(k,String(v)));const r=await fetch(base(),{method:'POST',body:b});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
  function topCodes(){return new Set((snapshot.sportifs||[]).slice(0,3).map(x=>x.code))}
  function renderSport(){const rows=snapshot.sportifs||[],e=$('#sportRanking');e.innerHTML=rows.length?rows.map((r,i)=>`<div class="ranking-row ${i<3?'podium-row':''}"><span class="rank-number">${i+1}</span><div><b>${esc(r.team)}</b><small>${r.places} lieu${r.places>1?'x':''} · ${r.returned?'revenue':'en jeu'}</small></div><strong>${r.points} pts</strong></div>`).join(''):'<p class="muted">Aucun score sportif pour le moment.</p>'}
  function renderTourists(){const rows=snapshot.touristes||[];$('#adminTourists').textContent=rows.length;$('#touristEligibleCount').textContent=`${rows.length} éligible${rows.length>1?'s':''}`;$('#drawTouristButton').disabled=!rows.length;$('#touristList').innerHTML=rows.length?rows.map(r=>`<div><b>${esc(r.team)}</b><span>${r.places} lieux</span></div>`).join(''):'<p class="muted">Aucune équipe éligible.</p>'}
  function renderTeams(){const rows=snapshot.teams||[];$('#teamCountBadge').textContent=rows.length;$('#teamTable').innerHTML=rows.length?`<div class="team-list">${rows.map(t=>`<div><span><b>${esc(t.name)}</b><small>${t.mode==='sportif'?'Sportifs':'Touristes'} · ${esc(t.code)}</small></span><strong class="${t.returnedAt?'ok':'wait'}">${t.returnedAt?'Revenue':'En jeu'}</strong></div>`).join('')}</div>`:'<p class="muted">Aucune équipe.</p>'}
  function renderProofs(){const top=topCodes();let rows=(snapshot.proofs||[]).filter(p=>top.has(p.code)).sort((a,b)=>String(a.team).localeCompare(String(b.team),'fr')||String(a.place).localeCompare(String(b.place),'fr'));$('#proofTableBody').innerHTML=rows.length?rows.map(p=>`<tr><td><button class="proof-thumb-button" data-preview="${esc(p.id)}" aria-label="Agrandir la photo"><span class="proof-thumb-loading">Chargement…</span><img class="proof-thumb" data-photo-id="${esc(p.id)}" alt="Preuve privée — ${esc(p.place)}"></button></td><td><b>${esc(p.team)}</b></td><td>${esc(p.place)}</td><td>${Number(p.points||0)}</td><td><div class="proof-actions"><a class="secondary-button tiny-button" href="${esc(p.photo)}" target="_blank" rel="noopener">Drive</a>${p.status==='rejected'?`<button class="primary-button tiny-button" data-status="valid" data-id="${esc(p.id)}">Rétablir</button>`:`<button class="danger-button tiny-button" data-status="rejected" data-id="${esc(p.id)}">Invalider</button>`}</div></td></tr>`).join(''):'<tr><td colspan="5" class="muted">Aucune preuve pour le podium actuel.</td></tr>';loadPrivateThumbnails()}
  async function loadPrivateThumbnails(){const imgs=[...document.querySelectorAll('img[data-photo-id]')];await Promise.all(imgs.map(async img=>{if(img.dataset.loaded==='1')return;try{const d=await get({action:'photo',pin:C.adminCode,id:img.dataset.photoId,t:Date.now()});if(d.ok===false)throw Error(d.error||'Photo indisponible');img.src=`data:${d.mime||'image/jpeg'};base64,${d.base64}`;img.dataset.loaded='1';img.closest('.proof-thumb-button')?.classList.add('is-loaded')}catch(_){const b=img.closest('.proof-thumb-button');if(b){b.classList.add('is-error');const l=b.querySelector('.proof-thumb-loading');if(l)l.textContent='Indisponible'}}}))}
  function openPreview(id){const img=document.querySelector(`img[data-photo-id="${CSS.escape(id)}"]`);if(!img?.src||!img.src.startsWith('data:'))return;let d=$('#photoPreviewDialog');if(!d){d=document.createElement('dialog');d.id='photoPreviewDialog';d.className='photo-preview-dialog';d.innerHTML='<button class="photo-preview-close" aria-label="Fermer">×</button><img alt="Aperçu privé de la preuve">';document.body.appendChild(d);d.querySelector('.photo-preview-close').onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()}}d.querySelector('img').src=img.src;d.showModal()}
  async function refresh(){const status=$('#adminApiStatus');status.textContent='Actualisation…';try{const d=await get({action:'admin',pin:C.adminCode,t:Date.now()});if(d.ok===false)throw Error(d.error||'Accès refusé');snapshot=d;$('#adminTeams').textContent=d.teams?.length||0;$('#adminProofs').textContent=(d.proofs||[]).filter(p=>p.status!=='rejected').length;$('#adminReturns').textContent=d.returns?.length||0;status.textContent=`Données actualisées à ${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`;renderSport();renderTourists();renderTeams();renderProofs()}catch(e){status.textContent=`Connexion impossible : ${e.message}`}}
  async function changeStatus(id,status){try{const d=await post({action:'updatestatus',pin:C.adminCode,id,status});if(d.ok===false)throw Error(d.error||'Modification refusée');toast(status==='rejected'?'Étape invalidée':'Étape rétablie');await refresh()}catch(e){toast(e.message)}}
  function draw(){const rows=snapshot.touristes||[];if(!rows.length)return;const winner=rows[Math.floor(Math.random()*rows.length)];$('#drawResult').innerHTML=`<span>🎉</span><strong>${esc(winner.team)}</strong><small>${winner.places} lieux comptabilisés</small>`}
  async function resetGame(){if($('#resetConfirmInput').value.trim().toUpperCase()!=='REINITIALISER'){ $('#resetMessage').textContent='Saisissez exactement REINITIALISER.';return }const b=$('#confirmResetButton');b.disabled=true;b.textContent='Effacement…';$('#resetMessage').textContent='';try{const d=await post({action:'resetgame',pin:C.adminCode});if(d.ok===false)throw Error(d.error||'Réinitialisation refusée');localStorage.clear();sessionStorage.setItem('jze_admin','1');$('#resetDialog').close();$('#resetConfirmInput').value='';toast('Jeu entièrement réinitialisé');await refresh()}catch(e){$('#resetMessage').textContent=e.message}finally{b.disabled=false;b.textContent='Tout effacer'}}
  function login(){if($('#adminCodeInput').value.trim()!==C.adminCode){$('#adminLoginMessage').textContent='Code incorrect.';return}sessionStorage.setItem('jze_admin','1');show();toast('Console ouverte')}
  function show(){const ok=sessionStorage.getItem('jze_admin')==='1';$('#adminLogin').classList.toggle('hidden',ok);$('#adminDashboard').classList.toggle('hidden',!ok);$('#adminLogoutButton').classList.toggle('hidden',!ok);if(ok)refresh()}
  $('#adminLoginButton').onclick=login;$('#adminCodeInput').onkeydown=e=>{if(e.key==='Enter')login()};$('#adminLogoutButton').onclick=()=>{sessionStorage.removeItem('jze_admin');show()};$('#adminRefreshButton').onclick=refresh;$('#drawTouristButton').onclick=draw;$('#resetGameButton').onclick=()=>{$('#resetMessage').textContent='';$('#resetConfirmInput').value='';$('#resetDialog').showModal()};$('#confirmResetButton').onclick=resetGame;document.addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(b)changeStatus(b.dataset.id,b.dataset.status);const p=e.target.closest('[data-preview]');if(p)openPreview(p.dataset.preview)});show();
})();
