(() => {
  'use strict';
  const C=window.JZE_CONFIG,$=s=>document.querySelector(s);let snapshot={teams:[],proofs:[],sportifs:[],touristes:[]};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('is-visible');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('is-visible'),2200)};
  async function get(params){const query=Object.entries(params).map(([k,v])=>`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join('&');const base=String(C.apiUrl||'').trim();if(!/^https:\/\//i.test(base))throw Error('URL Apps Script invalide');const url=`${base}${base.includes('?')?'&':'?'}${query}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
  async function post(params){const base=String(C.apiUrl||'').trim();if(!/^https:\/\//i.test(base))throw Error('URL Apps Script invalide');const b=new URLSearchParams();Object.entries(params).forEach(([k,v])=>b.set(k,String(v)));const r=await fetch(base,{method:'POST',body:b});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
  function sportCodes(){return new Set((snapshot.sportifs||[]).slice(0,5).map(x=>x.code))}
  function renderSport(){const rows=snapshot.sportifs||[],e=$('#sportRanking');e.innerHTML=rows.length?rows.map((r,i)=>`<div class="ranking-row"><span class="rank-number">${i+1}</span><div><b>${esc(r.team)}</b><small>${r.places} lieux · ${r.returned?'revenue':'pas encore revenue'}</small></div><strong>${r.points} pts</strong></div>`).join(''):'<p class="muted">Aucun score pour le moment.</p>'}
  function renderTourists(){const rows=snapshot.touristes||[];$('#adminTourists').textContent=rows.length;$('#touristEligibleCount').textContent=`${rows.length} éligible${rows.length>1?'s':''}`;$('#drawTouristButton').disabled=!rows.length}
  function renderTeams(){const rows=snapshot.teams||[];$('#teamTable').innerHTML=rows.length?`<div class="team-list">${rows.map(t=>`<div><span><b>${esc(t.name)}</b><small>${esc(t.mode==='sportif'?'Sportifs':'Touristes')} · ${esc(t.code)}</small></span><strong class="${t.returnedAt?'ok':'wait'}">${t.returnedAt?'Revenue':'En jeu'}</strong></div>`).join('')}</div>`:'<p class="muted">Aucune équipe.</p>'}
  function renderProofs(){const filter=$('#proofFilter').value,top=sportCodes();let rows=snapshot.proofs||[];if(filter==='top')rows=rows.filter(p=>top.has(p.code));if(filter==='rejected')rows=rows.filter(p=>p.status==='rejected');rows=rows.slice().sort((a,b)=>String(b.time).localeCompare(String(a.time)));$('#proofTableBody').innerHTML=rows.length?rows.map(p=>`<tr><td><b>${esc(p.team)}</b></td><td>${esc(p.place)}</td><td>${Number(p.points||0)}</td><td><span class="status-chip ${p.status}">${p.status==='rejected'?'Invalidée':'Validée'}</span></td><td><div class="proof-actions"><a class="secondary-button tiny-button" href="${esc(p.photo)}" target="_blank" rel="noopener">Ouvrir Drive</a>${p.status==='rejected'?`<button class="primary-button tiny-button" data-status="valid" data-id="${esc(p.id)}">Rétablir</button>`:`<button class="danger-button tiny-button" data-status="rejected" data-id="${esc(p.id)}">Invalider</button>`}</div></td></tr>`).join(''):'<tr><td colspan="5" class="muted">Aucune preuve à afficher.</td></tr>'}
  async function refresh(){const status=$('#adminApiStatus');status.textContent='Actualisation…';try{const d=await get({action:'admin',pin:C.adminCode,t:Date.now()});if(d.ok===false)throw Error(d.error||'Accès refusé');snapshot=d;$('#adminTeams').textContent=d.teams?.length||0;$('#adminProofs').textContent=(d.proofs||[]).filter(p=>p.status!=='rejected').length;$('#adminReturns').textContent=d.returns?.length||0;status.textContent=`Données actualisées à ${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`;renderSport();renderTourists();renderTeams();renderProofs()}catch(e){status.textContent=`Connexion impossible : ${e.message}`}}
  async function changeStatus(id,status){try{const d=await post({action:'updatestatus',pin:C.adminCode,id,status});if(d.ok===false)throw Error(d.error||'Modification refusée');toast(status==='rejected'?'Preuve invalidée':'Preuve rétablie');await refresh()}catch(e){toast(e.message)}}
  function draw(){const rows=snapshot.touristes||[];if(!rows.length)return;const winner=rows[Math.floor(Math.random()*rows.length)];$('#drawResult').innerHTML=`<span>🎉</span><strong>${esc(winner.team)}</strong><small>${winner.places} lieux validés</small>`}
  function login(){if($('#adminCodeInput').value.trim()!==C.adminCode){$('#adminLoginMessage').textContent='Code incorrect.';return}sessionStorage.setItem('jze_admin','1');show();toast('Poste de pilotage ouvert')}
  function show(){const ok=sessionStorage.getItem('jze_admin')==='1';$('#adminLogin').classList.toggle('hidden',ok);$('#adminDashboard').classList.toggle('hidden',!ok);$('#adminLogoutButton').classList.toggle('hidden',!ok);if(ok)refresh()}
  $('#adminLoginButton').onclick=login;$('#adminCodeInput').onkeydown=e=>{if(e.key==='Enter')login()};$('#adminLogoutButton').onclick=()=>{sessionStorage.removeItem('jze_admin');show()};$('#adminRefreshButton').onclick=refresh;$('#drawTouristButton').onclick=draw;$('#proofFilter').onchange=renderProofs;document.addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(b)changeStatus(b.dataset.id,b.dataset.status)});show();
})();
