(() => {
  'use strict';
  const C=window.JZE_CONFIG, PLACES=window.JZE_PLACES;
  const routes=['accueil','explorer','equipe','classement'];
  const state={team:load('jze_team',null),proofs:load('jze_proofs',[]),returned:load('jze_returned',false),selectedMode:null,activeFilter:'tous',installPrompt:null,activePlace:null,photoData:null,photoMime:'image/jpeg'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
  function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
  function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('is-visible');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('is-visible'),2600)}
  function route(){const raw=location.hash.slice(1).toLowerCase(),cur=routes.includes(raw)?raw:'accueil';$$('.screen').forEach(x=>x.classList.toggle('is-active',x.id===cur));$$('.bottom-nav a').forEach(x=>x.classList.toggle('is-active',x.dataset.route===cur));document.title=`${C.appName} — ${$(`#${cur}`).dataset.title}`;scrollTo({top:0,behavior:'instant'});if(cur==='classement')loadRanking()}
  function saveTeam(t){state.team=t;save('jze_team',t);renderTeam()}
  function saveProofs(){save('jze_proofs',state.proofs);renderTeam();renderPlaces()}
  function teamProofs(){return state.team?state.proofs.filter(p=>p.teamCode===state.team.code):[]}
  function placeById(id){return PLACES.find(p=>String(p.id)===String(id))}
  function teamPoints(){const seen=new Set();return teamProofs().reduce((sum,p)=>{const id=String(p.placeId);if(seen.has(id)||p.status==='rejected')return sum;seen.add(id);return sum+(placeById(id)?.points||0)},0)}
  function renderTeam(){const t=state.team,has=!!t;$('#welcomeCard')?.classList.toggle('hidden',has);$('#teamReadyCard')?.classList.toggle('hidden',!has);$('#teamEmptyState').classList.toggle('hidden',has);$('#teamPanel').classList.toggle('hidden',!has);if(has){$('#teamPanelName').textContent=t.name;$('#teamPanelMeta').textContent=`Code : ${t.code} · Série : ${t.mode==='sportif'?'Sportifs':'Touristes'}`;}const unique=new Set(teamProofs().filter(p=>p.status!=='rejected').map(p=>String(p.placeId)));$('#teamPlacesCount').textContent=String(unique.size);$('#teamPointsCount').textContent=String(teamPoints());$('#teamReturnStatus').textContent=state.returned?'Oui':'Non';$('#markReturnButton').disabled=state.returned;$('#markReturnButton').textContent=state.returned?'Retour signalé ✓':'Signaler notre retour'}
  function openTeam(){state.selectedMode=state.team?.mode||null;$('#teamNameInput').value=state.team?.name||'';$('#teamCodeInput').value=state.team?.code||'';$('#teamFormMessage').textContent='';$$('.mode-grid button').forEach(b=>b.classList.toggle('is-selected',b.dataset.mode===state.selectedMode));$('#teamModal').classList.add('is-open');$('#teamModal').setAttribute('aria-hidden','false')}
  function closeTeam(){$('#teamModal').classList.remove('is-open');$('#teamModal').setAttribute('aria-hidden','true')}
  async function submitTeam(){const name=$('#teamNameInput').value.trim(),code=$('#teamCodeInput').value.trim().toUpperCase();if(name.length<2)return $('#teamFormMessage').textContent='Saisissez un nom d’équipe.';if(code.length<3)return $('#teamFormMessage').textContent='Saisissez un code d’au moins 3 caractères.';if(!state.selectedMode)return $('#teamFormMessage').textContent='Choisissez une série.';const team={name,code,mode:state.selectedMode,updatedAt:new Date().toISOString()};$('#saveTeamButton').disabled=true;try{const d=await post({action:'register',team:JSON.stringify(team)});if(d?.ok===false)throw Error(d.error||'Enregistrement refusé');saveTeam(team);closeTeam();toast('Équipe enregistrée')}catch(e){saveTeam(team);closeTeam();toast('Équipe enregistrée sur ce téléphone')}finally{$('#saveTeamButton').disabled=false}}
  function renderFilters(){const labels={tous:'Tous',patrimoine:'Patrimoine',culture:'Culture',sport:'Sport',nature:'Nature',insolite:'Insolite',pratique:'Pratique'};$('#filters').innerHTML=Object.entries(labels).map(([k,l])=>`<button data-filter="${k}" class="${k==='tous'?'is-active':''}">${l}</button>`).join('')}
  function proofFor(id){return state.team&&state.proofs.find(p=>p.teamCode===state.team.code&&String(p.placeId)===String(id)&&p.status!=='rejected')}
  function renderPlaces(){const list=state.activeFilter==='tous'?PLACES:PLACES.filter(p=>p.category===state.activeFilter);$('#placeCounter').textContent=`${list.length} lieu${list.length>1?'x':''}`;$('#placesGrid').innerHTML=list.map(p=>{const proof=proofFor(p.id);return `<button type="button" class="card place-card place-button ${proof?'is-submitted':''}" data-place-id="${p.id}"><div class="place-emoji">${p.emoji}</div><div class="place-content"><div class="place-title-row"><h3>${esc(p.name)}</h3>${proof?'<span class="submitted-badge">Validé</span>':''}</div><p>${esc(p.description)}</p><div class="place-meta"><span>${esc(p.distance)}</span><span>${p.points} points</span></div><span class="mission-link">${proof?'Voir la mission':'Ouvrir la mission'} →</span></div></button>`}).join('')}
  function resetPhoto(){state.photoData=null;$('#missionCameraInput').value='';$('#missionGalleryInput').value='';$('#photoPreview').removeAttribute('src');$('#photoPreviewWrap').classList.add('hidden');$('#photoSourceGrid').classList.remove('hidden');$('#sendProofButton').disabled=true;$('#sendProofButton').textContent='Envoyer la preuve';$('#uploadStatus').textContent=''}
  function openMission(id){const p=placeById(id);if(!p)return;state.activePlace=p;resetPhoto();$('#missionEmoji').textContent=p.emoji;$('#missionTitle').textContent=p.name;$('#missionDescription').textContent=p.description;$('#missionInstruction').textContent=p.mission;$('#missionPoints').textContent=`Cette étape rapporte ${p.points} points.`;const no=!state.team,done=!!proofFor(p.id);$('#missionTeamWarning').classList.toggle('hidden',!no);['#takePhotoButton','#choosePhotoButton','#missionCameraInput','#missionGalleryInput'].forEach(sel=>$(sel).disabled=no||done);if(done){$('#photoSourceGrid').classList.add('hidden');$('#uploadStatus').textContent='Cette étape est déjà validée pour votre équipe.';$('#sendProofButton').textContent='Étape validée ✓'}$('#missionModal').classList.add('is-open');$('#missionModal').setAttribute('aria-hidden','false')}
  function closeMission(){$('#missionModal').classList.remove('is-open');$('#missionModal').setAttribute('aria-hidden','true');resetPhoto()}
  const read=f=>new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>no(Error('Lecture impossible'));r.readAsDataURL(f)});
  const image=src=>new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('Image non reconnue'));i.src=src});
  async function compress(file){const src=await read(file),img=await image(src),max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d',{alpha:false}).drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.72)}
  async function handlePhoto(file){if(!file)return;$('#uploadStatus').textContent='Préparation…';try{state.photoData=await compress(file);$('#photoPreview').src=state.photoData;$('#photoPreviewWrap').classList.remove('hidden');$('#photoSourceGrid').classList.add('hidden');$('#uploadStatus').textContent='Photo prête.';$('#sendProofButton').disabled=false}catch(e){resetPhoto();$('#uploadStatus').textContent=e.message}}
  async function sendProof(){if(!state.team)return openTeam();if(!state.activePlace||!state.photoData)return;const b=$('#sendProofButton');b.disabled=true;b.textContent='Envoi…';$('#uploadStatus').textContent='Envoi sécurisé vers Google Drive…';try{const d=await post({action:'submit',team:JSON.stringify(state.team),place:JSON.stringify({id:state.activePlace.id,name:state.activePlace.name}),photoBase64:state.photoData,mimeType:'image/jpeg'});if(!d||d.ok===false)throw Error(d?.error||'Envoi refusé');state.proofs=state.proofs.filter(p=>!(p.teamCode===state.team.code&&String(p.placeId)===String(state.activePlace.id)));state.proofs.push({id:d.id||String(Date.now()),teamCode:state.team.code,placeId:state.activePlace.id,placeName:state.activePlace.name,status:d.status||'valid',points:d.points||state.activePlace.points,sentAt:new Date().toISOString()});saveProofs();$('#uploadStatus').textContent=`Étape validée : +${d.points||state.activePlace.points} points.`;b.textContent='Étape validée ✓';toast('Étape validée');setTimeout(closeMission,1100)}catch(e){$('#uploadStatus').textContent=`Échec : ${e.message}`;b.disabled=false;b.textContent='Réessayer'}}
  async function markReturn(){if(!state.team)return openTeam();const b=$('#markReturnButton');b.disabled=true;$('#returnMessage').textContent='Enregistrement du retour…';try{const d=await post({action:'return',team:JSON.stringify(state.team),time:new Date().toISOString()});if(d?.ok===false)throw Error(d.error||'Retour refusé');state.returned=true;save('jze_returned',true);renderTeam();$('#returnMessage').textContent='Retour enregistré. Merci !';toast('Retour enregistré')}catch(e){b.disabled=false;$('#returnMessage').textContent='Impossible de signaler le retour. Réessayez.'}}
  async function get(params){const query=Object.entries(params).map(([k,v])=>`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join('&');const base=String(C.apiUrl||'').trim();if(!/^https:\/\//i.test(base))throw Error('URL Apps Script invalide');const url=`${base}${base.includes('?')?'&':'?'}${query}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
  async function post(params){const base=String(C.apiUrl||'').trim();if(!/^https:\/\//i.test(base))throw Error('URL Apps Script invalide');const body=new URLSearchParams();Object.entries(params).forEach(([k,v])=>body.set(k,String(v)));const r=await fetch(base,{method:'POST',body});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
  async function loadRanking(){const st=$('#rankingStatus'),list=$('#rankingList');st.textContent='Chargement…';list.innerHTML='';try{const data=await get({action:'ranking',t:Date.now()}),rows=data.sportifs||data.ranking||[];if(!rows.length){st.textContent='Aucun score sportif pour le moment.';return}st.textContent=`Actualisé à ${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`;list.innerHTML=rows.map((r,i)=>`<div class="ranking-row"><span class="rank-number">${i+1}</span><div><b>${esc(r.team||r.name)}</b><small>${r.places||r.validated||0} lieu${(r.places||0)>1?'x':''} validé${(r.places||0)>1?'s':''}</small></div><strong>${r.points||r.score||0} pts</strong></div>`).join('')}catch(e){st.textContent='Classement indisponible.';list.innerHTML=`<p class="form-message">${esc(e.message)}</p>`}}
  function install(){addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('#installButton').hidden=true}}
  if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
  addEventListener('hashchange',route);document.addEventListener('click',e=>{if(e.target.closest('[data-open-team]')){e.preventDefault();openTeam()}if(e.target.closest('[data-close-modal]'))closeTeam();if(e.target.closest('[data-close-mission]'))closeMission();const m=e.target.closest('[data-mode]');if(m){state.selectedMode=m.dataset.mode;$$('.mode-grid button').forEach(b=>b.classList.toggle('is-selected',b===m))}const f=e.target.closest('[data-filter]');if(f){state.activeFilter=f.dataset.filter;$$('[data-filter]').forEach(b=>b.classList.toggle('is-active',b===f));renderPlaces()}const p=e.target.closest('[data-place-id]');if(p)openMission(p.dataset.placeId)});
  $('#saveTeamButton').onclick=submitTeam;$('#refreshRanking').onclick=loadRanking;$('#takePhotoButton').onclick=()=>$('#missionCameraInput').click();$('#choosePhotoButton').onclick=()=>$('#missionGalleryInput').click();$('#missionCameraInput').onchange=e=>handlePhoto(e.target.files?.[0]);$('#missionGalleryInput').onchange=e=>handlePhoto(e.target.files?.[0]);$('#changePhotoButton').onclick=()=>{resetPhoto();$('#missionGalleryInput').click()};$('#sendProofButton').onclick=sendProof;$('#markReturnButton').onclick=markReturn;

  document.addEventListener('jze:open-place',e=>openMission(e.detail));
  document.addEventListener('jze:focus-place',e=>window.JZE_MAP?.focusPlace(e.detail));
  renderFilters();renderPlaces();renderTeam();route();install();window.JZE_MAP?.init();
})();
